### ISSUE TITLE
cypheroth can't find cypher-shell

### ISSUE THREAD

**Issue by barrett092** [seajaysec/cypheroth#1]
Have tried putting the cypher-shell in the same folder. No luck. 
Also confirmed cypher-shell is installed in bin folder of Neo4j. 

OS: Mac OS Mojave
Neo4J 1.22-dev.5
DB 4.0.0-alpha09mr02 Enterprise

**Comment by seajaysec** [comment]
In the command line, what returns when you enter `which cypher-shell`?

**Comment by seajaysec** [comment]
I'm 99% certain that this is an issue with `cypher-shell` not being installed in your path properly. It might be a problem with the enterprise edition of neo4j though. I haven't tested that yet. So far, I'm aiming to support neo4j community as it has the widest install base.

If anyone else has this issue, please let me know and I'll continue to look into it. Otherwise, closing for now.
